# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DataSetModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_score', models.IntegerField(verbose_name='抽象化')),
                ('parallelism_score', models.IntegerField(verbose_name='并行')),
                ('synchronization_score', models.IntegerField(verbose_name='同步性')),
                ('flow_control_score', models.IntegerField(verbose_name='流控制')),
                ('user_interactivity_score', models.IntegerField(verbose_name='用户交互')),
                ('logical_thinking_score', models.IntegerField(verbose_name='逻辑性')),
                ('data_representation_score', models.IntegerField(verbose_name='数据表示')),
                ('total', models.IntegerField(verbose_name='总分')),
                ('hint', models.CharField(max_length=100, verbose_name='作品提示')),
                ('production_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DataSetModel.ScratchApiProduction', unique=True, verbose_name='作品ID')),
            ],
            options={
                'db_table': 'DataSet_CTModel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LearnModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('lesson_id', models.IntegerField()),
                ('chapter_id', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('learn_time', models.BigIntegerField(blank=True, null=True)),
                ('click_audio', models.IntegerField()),
            ],
            options={
                'db_table': 'DataSet_LearnModel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='用户名')),
                ('gender', models.CharField(blank=True, max_length=30, null=True, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('school', models.CharField(blank=True, max_length=50, null=True, verbose_name='学校')),
                ('grade', models.CharField(blank=True, max_length=40, null=True, verbose_name='年级')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='地区')),
                ('student_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='学号')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='手机号')),
                ('registration_time', models.DateTimeField(blank=True, null=True, verbose_name='注册时间')),
                ('coursetimes', models.IntegerField(blank=True, null=True, verbose_name='学习的课程数')),
                ('favtimes', models.IntegerField(blank=True, null=True, verbose_name='收藏的作品数')),
                ('creativetimes', models.IntegerField(blank=True, null=True, verbose_name='创作数')),
                ('remixtimes', models.IntegerField(blank=True, null=True, verbose_name='改编数')),
                ('course_list', models.TextField(blank=True, null=True, verbose_name='学习的课程列表')),
                ('production_list', models.TextField(blank=True, null=True, verbose_name='创作作品列表')),
                ('fav_list', models.TextField(blank=True, null=True, verbose_name='创作收藏列表')),
                ('remix_tree', models.TextField(blank=True, null=True, verbose_name='改编树')),
                ('learning_duration', models.IntegerField(blank=True, null=True, verbose_name='学习总时长')),
                ('active_level', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户活跃等级')),
            ],
            options={
                'db_table': 'DataSet_StudentModel',
                'managed': True,
            },
        ),
    ]
