# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalDataSetModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('teacher_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='用户名')),
                ('school', models.CharField(blank=True, max_length=50, null=True, verbose_name='学校')),
                ('teach_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='所教班级')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='手机号')),
                ('course_times', models.IntegerField(blank=True, default=0, null=True, verbose_name='创建课程数')),
                ('contest_times', models.IntegerField(blank=True, default=0, null=True, verbose_name='发起的竞赛数')),
                ('production_evalu', models.TextField(verbose_name='评价记录')),
            ],
            options={
                'db_table': 'DataSet_TeacherModel',
                'managed': True,
            },
        ),
    ]
