# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalDataSetModel', '0002_teachermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.IntegerField(unique=True, verbose_name='课程编号')),
                ('name', models.CharField(max_length=50, verbose_name='课程名')),
                ('short_introduction', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('author_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='出课老师')),
                ('learn_times', models.IntegerField(verbose_name='学习次数')),
            ],
            options={
                'db_table': 'DataSet_KnowModel_lesson',
                'managed': True,
            },
        ),
    ]
