# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalDataSetModel', '0004_auto_20181122_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowmodel1',
            name='lesson_id',
            field=models.IntegerField(verbose_name='课程编号'),
        ),
    ]
