# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalDataSetModel', '0005_auto_20181122_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowmodel',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='学习次数'),
        ),
    ]
