# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalDataSetModel', '0010_auto_20181122_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
        migrations.RemoveField(
            model_name='b',
            name='a',
        ),
        migrations.DeleteModel(
            name='TeacherModel1',
        ),
        migrations.DeleteModel(
            name='B',
        ),
    ]
