# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinalDataSetModel', '0011_auto_20181122_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowmodel1',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinalDataSetModel.KnowModel', verbose_name='课程编号'),
        ),
        migrations.RemoveField(
            model_name='knowmodel1',
            name='lesson_id',
        ),
        migrations.AlterUniqueTogether(
            name='knowmodel1',
            unique_together=set([('lesson', 'chapter_id')]),
        ),
    ]
