# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinalDataSetModel', '0012_auto_20181122_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowmodel',
            name='author_id',
        ),
        migrations.AddField(
            model_name='knowmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinalDataSetModel.TeacherModel', verbose_name='出课老师'),
        ),
    ]
