# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalDataSetModel', '0013_auto_20181122_1924'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='knowmodel1',
            unique_together=set([('lesson', 'chapter_id', 'name')]),
        ),
    ]
