# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinalDataSetModel', '0014_auto_20181122_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionModel',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='作品ID')),
                ('name', models.CharField(max_length=50, verbose_name='作品名称')),
                ('type', models.CharField(max_length=20, verbose_name='类型')),
                ('create_time', models.DateTimeField()),
                ('viewtimes', models.IntegerField(blank=True, default=0, null=True, verbose_name='浏览数')),
                ('liketimes', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞数')),
                ('favtimes', models.IntegerField(blank=True, default=0, null=True, verbose_name='被收藏数')),
                ('remixedtimes', models.IntegerField(blank=True, default=0, null=True, verbose_name='被改编数')),
                ('parent_id', models.CharField(max_length=32, verbose_name='改编来源')),
                ('lesson_id', models.IntegerField()),
                ('belong_class', models.CharField(blank=True, max_length=40, null=True, verbose_name='年级')),
                ('sb2file', models.CharField(max_length=100)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinalDataSetModel.StudentModel', verbose_name='作者')),
            ],
            options={
                'db_table': 'DataSet_ProductionModel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductionModelSb2Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion_num', models.IntegerField()),
                ('looklike_num', models.IntegerField()),
                ('sounds_num', models.IntegerField()),
                ('draw_num', models.IntegerField()),
                ('event_num', models.IntegerField()),
                ('control_num', models.IntegerField()),
                ('sensor_num', models.IntegerField()),
                ('operate_num', models.IntegerField()),
                ('more_num', models.IntegerField()),
                ('data_num', models.IntegerField()),
                ('sprite_num', models.IntegerField()),
                ('backdrop_num', models.IntegerField()),
                ('snd_num', models.IntegerField()),
                ('production_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalDataSetModel.ProductionModel', unique=True, verbose_name='作品ID')),
            ],
            options={
                'db_table': 'DataSet_ProductionModelSb2Profile',
                'managed': True,
            },
        ),
    ]
