# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalDataSetModel', '0015_productionmodel_productionmodelsb2profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionmodel',
            name='lesson_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionmodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='作品名称'),
        ),
        migrations.AlterField(
            model_name='productionmodel',
            name='parent_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='改编来源'),
        ),
        migrations.AlterField(
            model_name='productionmodel',
            name='sb2file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productionmodel',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='类型'),
        ),
    ]
