# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalDataSetModel', '0016_auto_20181122_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_type', models.CharField(max_length=10, verbose_name='作品ID')),
                ('operate_time', models.DateTimeField(verbose_name='操作时间')),
                ('operate_object', models.TextField(verbose_name='操作详情')),
                ('prod_id', models.CharField(max_length=32, verbose_name='作品ID')),
            ],
            options={
                'db_table': 'DataSet_ProcessModel',
                'managed': True,
            },
        ),
    ]
