# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-23 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinalDataSetModel', '0018_auto_20181122_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessModel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作类型')),
                ('op', models.CharField(blank=True, max_length=100, null=True, verbose_name='块名称')),
                ('loc', models.CharField(blank=True, max_length=100, null=True, verbose_name='块连接方式')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='操作时间')),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinalDataSetModel.ProductionModel', verbose_name='作品ID')),
            ],
            options={
                'db_table': 'DataSet_ProcessModel_block',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProcessModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spr_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作类型')),
                ('spr_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='角色名称')),
                ('spr_from', models.CharField(blank=True, max_length=100, null=True, verbose_name='角色来源')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='操作时间')),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinalDataSetModel.ProductionModel', verbose_name='作品ID')),
            ],
            options={
                'db_table': 'DataSet_ProcessModel_sprite',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProcessModel3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作方式')),
                ('obj_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='资源类型')),
                ('obj_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='资源名称')),
                ('obj_from', models.CharField(blank=True, max_length=100, null=True, verbose_name='资源来源')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='操作时间')),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinalDataSetModel.ProductionModel', verbose_name='作品ID')),
            ],
            options={
                'db_table': 'DataSet_ProcessModel_backdrop_sound_costume',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='ProcessModel',
        ),
    ]
