# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-23 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinalDataSetModel', '0019_auto_20181123_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctmodel',
            name='production_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FinalDataSetModel.ProductionModel', unique=True, verbose_name='作品ID'),
        ),
    ]
