# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-23 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalDataSetModel', '0020_auto_20181123_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionmodel',
            name='viewtimes',
        ),
    ]
