# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-23 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalDataSetModel', '0021_remove_productionmodel_viewtimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='coursetimes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='学习的课程数'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='creativetimes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='创作数'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='favtimes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏的作品数'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='remixtimes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='改编数'),
        ),
    ]
